---
name: Prepare, build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux-x86-64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install needed packages
        run: |
          sudo apt update
          sudo apt install -y git \
                              build-essential \
                              cmake \
                              clang \
                              meson \
                              pkg-config

      - name: Configure and Build
        run: |
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/tests
          ./criterion_playground_tests


  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install needed software
        run: |
          brew update && \
          brew install meson

      - name: Build
        run: |
          cd build
          #export C_INCLUDE_PATH=/usr/local/include
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/tests
          ./criterion_playground_tests
